[project]
name = "railroad_1959"
version = "0.1.10"
description = "Railroad Engineer 1959 RL Environment"
readme = "README.md"
requires-python = ">=3.10"
tags = [
    "railroad",
    "operations",
    "safety",
    "rl",
    "tinker",
    "primeintellect",
    "1959",
]
dependencies = [
    "verifiers",
    "python-dotenv",
    "requests",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
